// React.JS/Lab 2/product_gallery/src/components/ProductCard.tsx
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardDescription, CardFooter, CardHeader, CardTitle } from "@/components/ui/card";
import type { IProduct } from "@/types/types";
import { Star } from "lucide-react";

const ProductCard = ({ product }: { product: IProduct }) => {
  const isPremium = product.price > 100;
  const badgeLabel = isPremium ? "Premium" : "Best Seller";
  const badgeColor = isPremium ? "bg-blue-600" : "bg-green-600";

  return (
    <Card className="mx-auto flex w-full max-w-sm flex-col overflow-hidden transition-all duration-200 hover:shadow-md">
      <div className="group relative aspect-video w-full overflow-hidden bg-muted">
        <div className="absolute inset-0 z-10 bg-black/10 transition-colors duration-300 group-hover:bg-transparent" />

        <div className="absolute left-3 top-3 z-20">
          <Badge variant="secondary" className="bg-background/80 font-medium backdrop-blur-md">
            {product.category}
          </Badge>
        </div>

        <div className="absolute right-3 top-3 z-20">
          <Badge className={`${badgeColor} text-white font-medium border-none shadow-sm`}>{badgeLabel}</Badge>
        </div>

        <img src={product.image} alt={product.title} loading="lazy" className="h-full w-full object-cover transition-transform duration-500 group-hover:scale-105" />
      </div>
      <CardHeader className="flex-1 space-y-3">
        <CardTitle className="line-clamp-1 text-lg" title={product.title}>
          {product.title}
        </CardTitle>

        <CardDescription className="line-clamp-2 text-sm">{product.description}</CardDescription>

        <div className="flex items-center justify-between gap-2 pt-1">
          <div className="flex items-center gap-1.5 text-sm font-medium">
            <Star className="h-4 w-4 fill-amber-400 text-amber-400" aria-hidden="true" />
            <span>{product.rating.rate.toFixed(1)}</span>
            <span className="font-normal text-muted-foreground text-xs">({product.rating.count})</span>
          </div>

          <span className="text-xl font-bold text-primary">${product.price.toFixed(2)}</span>
        </div>
      </CardHeader>

      <CardFooter className="pt-0">
        <Button className="w-full py-5 transition-transform active:scale-[0.98]">Add to Cart</Button>
      </CardFooter>
    </Card>
  );
};

export default ProductCard;

// Vue.Js/lab_2/src/components/utils/ProductCard.vue
<script setup lang="ts">
import { computed } from "vue";
import type { productProps } from "../../types/types";

const props = defineProps<{
  product: productProps;
}>();

const discountedPrice = computed(() => {
  return props.product.price - (props.product.price * props.product.discount) / 100;
});

const getDiscountClass = computed(() => {
  return props.product.discount > 0 ? "line-through" : "";
});
const getCTAClass = computed(() => {
  return props.product.stock > 0 ? "btn-primary" : "btn-error";
});

const getCTABadge = computed(() => {
  if (props.product.stock > 0) {
    return props.product.badge;
  } else {
    return "Out of Stock";
  }
});

const emit = defineEmits<{
  (event: "buy", productId: number): void;
}>();

const handleBuy = () => {
  emit("buy", props.product.id);
};
</script>
<template>
  <article class="flex flex-col gap-3 p-4 border border-slate-200 rounded-xl bg-white shadow-sm hover:-translate-y-1 hover:shadow-lg transition duration-200">
    <RouterLink :to="`/products/${props.product.id}`" class="block">
      <div class="relative">
        <img :src="props.product.image" :alt="props.product.name" class="w-full h-44 object-cover rounded-lg" />
        <span v-show="props.product.badge !== ''" class="absolute left-2 top-2 inline-flex items-center px-2 py-1 rounded-full bg-blue-100 text-blue-700 text-xs font-bold tracking-wide">{{ getCTABadge }}</span>
      </div>
      <h3 class="m-0 mt-3 text-lg text-slate-900 font-semibold">{{ props.product.name }}</h3>
    </RouterLink>

    <p class="m-0 text-slate-600 leading-6">{{ props.product.description }}</p>
    <div class="space-y-1 flex items-center gap-2">
      <p :class="getDiscountClass">${{ props.product.price.toFixed(2) }}</p>
      <p v-if="props.product.discount > 0" class="text-slate-900 font-semibold">${{ discountedPrice.toFixed(2) }}</p>
    </div>

    <ul class="list-none m-0 p-0 flex flex-wrap gap-2">
      <li v-for="tag in props.product.tags" :key="tag" class="px-2 py-1 text-xs text-slate-700 border border-slate-300 rounded-full">
        {{ tag }}
      </li>
    </ul>

    <button :disabled="props.product.stock <= 0" :class="getCTAClass" class="mt-1" @click="handleBuy">Buy Now</button>
  </article>
</template>
