// Next.Js/Lab_1/abdostore/src/components/ProductCard.tsx
import Link from "next/link";
import Image from "next/image";
import { Product } from "@/types/index";

export default function ProductCard({ product }: { product: Product }) {
  return (
    <Link href={`/products/${product.id}`} className="group flex h-full">
      <div className="flex flex-col w-full bg-white border border-gray-200 rounded-xl overflow-hidden shadow-sm hover:shadow-xl transition-all duration-300 cursor-pointer">
        
        <div className="relative w-full h-48 bg-gray-50 overflow-hidden">
          <Image 
            src={product.thumbnail} 
            alt={product.title} 
            fill
            sizes="(max-width: 768px) 100vw, (max-width: 1200px) 50vw, 33vw"
            className="object-cover transition-transform duration-300 group-hover:scale-105" 
          />
        </div>

        <div className="p-5 flex flex-col flex-grow">
          <h2 className="text-lg font-bold text-gray-900 truncate mb-1">
            {product.title}
          </h2>
          
          <p className="text-sm text-gray-500 line-clamp-2 mb-4 flex-grow">
            {product.description}
          </p>
          
          <div className="mt-auto pt-4 flex justify-between items-center border-t border-gray-100">
            <span className="text-xl font-black text-gray-900">
              ${product.price}
            </span>
            <span className="flex items-center gap-1 px-2 py-1 bg-yellow-50 text-yellow-700 text-sm font-semibold rounded-md">
              <span className="text-yellow-500">★</span> 
              {product.rating.toFixed(1)}
            </span>
          </div>
        </div>

      </div>
    </Link>
  );
}

// Vue.Js/lab_1/src/components/ProductCard.vue
<script setup lang="ts">
interface Product {
  id: number;
  name: string;
  description: string;
  image: string;
  badge: string;
  price: number;
  discount: number;
  tags: string[];
  isAvailable: boolean;
}

const props = defineProps<{
  product: Product;
}>();

import { computed } from "vue";

const discountedPrice = computed(() => {
  return props.product.price - (props.product.price * props.product.discount) / 100;
});

const getDiscountClass = computed(() => {
  return props.product.discount > 0 ? "line-through" : "";
});
const getCTAClass = computed(() => {
  return props.product.isAvailable ? "btn-primary" : "btn-error";
});

const getCTABadge = computed(() => {
  if (props.product.isAvailable) {
    return props.product.badge;
  } else {
    return "Out of Stock";
  }
});
</script>
<template>
  <div class="flex flex-col gap-3 p-4 border border-slate-200 rounded-xl bg-white shadow-sm hover:-translate-y-1 hover:shadow-lg transition duration-200">
    <img :src="props.product.image" :alt="props.product.name" class="w-full h-44 object-cover rounded-lg" />
    <span v-show="props.product.badge !== ''" class="inline-flex w-fit items-center px-2 py-1 rounded-full bg-blue-100 text-blue-700 text-xs font-bold tracking-wide">{{ getCTABadge }}</span>
    <h3 class="m-0 text-lg text-slate-900 font-semibold">{{ props.product.name }}</h3>
    <p class="m-0 text-slate-600 leading-6">{{ props.product.description }}</p>
    <div class="space-y-1">
      <p :class="getDiscountClass">${{ props.product.price.toFixed(2) }}</p>
      <p v-if="props.product.discount > 0" class="text-slate-900 font-semibold">${{ discountedPrice.toFixed(2) }}</p>
    </div>

    <ul class="list-none m-0 p-0 flex flex-wrap gap-2">
      <li v-for="tag in props.product.tags" :key="tag" class="px-2 py-1 text-xs text-slate-700 border border-slate-300 rounded-full">
        {{ tag }}
      </li>
    </ul>
    <button :disabled="!props.product.isAvailable" :class="getCTAClass" class="mt-1">Buy Now</button>
  </div>
</template>
