// Vue.Js/lab_2/src/components/utils/NavBar.vue
<script setup lang="ts">
import { computed, onMounted, onUnmounted } from "vue";
import type { productProps } from "../../types/types";

const props = defineProps<{
  products: productProps[];
}>();

const totalStock = computed(() => {
  return props.products.reduce((total, product) => total + product.stock, 0);
});

onMounted(() => {
  console.log("NavBar mounted");
});

onUnmounted(() => {
  console.log("NavBar unmounted");
});
</script>

<template>
  <header class="sticky top-0 z-40 border-b border-slate-200 bg-white/90 backdrop-blur">
    <div class="mx-auto flex w-[min(1100px,92vw)] flex-wrap items-center justify-between gap-3 py-3 md:py-4">
      <RouterLink to="/" class="text-xl font-bold tracking-tight text-slate-900 md:text-2xl">My Store</RouterLink>

      <nav aria-label="Main navigation" class="order-3 w-full md:order-2 md:w-auto">
        <ul class="flex w-full items-center gap-2 overflow-x-auto pb-1 text-sm text-slate-600 md:w-auto md:justify-center md:gap-6 md:overflow-visible md:pb-0 md:text-base">
          <li>
            <RouterLink to="/" class="inline-flex rounded-md px-3 py-1.5 transition hover:bg-slate-100 hover:text-slate-900">Home</RouterLink>
          </li>
          <li>
            <RouterLink to="/products" class="inline-flex rounded-md px-3 py-1.5 transition hover:bg-slate-100 hover:text-slate-900">Products</RouterLink>
          </li>
          <li>
            <RouterLink to="/about" class="inline-flex rounded-md px-3 py-1.5 transition hover:bg-slate-100 hover:text-slate-900">About</RouterLink>
          </li>
        </ul>
      </nav>

      <div class="order-2 flex items-center gap-2 rounded-full bg-slate-100 px-3 py-1.5 text-sm text-slate-700 md:order-3">
        <span class="font-semibold text-slate-900">Stock</span>
        <span class="rounded-full bg-slate-900 px-2 py-0.5 text-xs font-semibold text-white">{{ totalStock }}</span>
      </div>
    </div>
  </header>
</template>

// Next.Js/Lab_1/abdostore/src/components/Navbar.tsx
import Link from "next/link";

export default function Navbar() {
  return (
    <nav className="bg-gradient-to-r from-gray-900 via-slate-800 to-gray-900 text-white shadow-lg sticky top-0 z-50 border-b border-gray-800">
      <div className="container mx-auto px-6 py-4 flex justify-between items-center">
        <Link href="/" className="text-2xl font-extrabold tracking-wider text-transparent bg-clip-text bg-gradient-to-r from-blue-400 to-purple-400 hover:opacity-80 transition-opacity">
          AbdoStore
        </Link>

        <div className="flex items-center space-x-8">
          <Link href="/products" className="text-base font-medium text-gray-300 hover:text-white transition-colors relative group">
            Products
            <span className="absolute -bottom-1 left-0 w-0 h-0.5 bg-blue-400 transition-all duration-300 group-hover:w-full"></span>
          </Link>
        </div>
      </div>
    </nav>
  );
}
